import { IVideoListPageInfo } from '../../common/interfaces/IVideoListPageInfo'

export const directorProducerPageInfo: IVideoListPageInfo = {
  pageTitle: 'Director & Producer',
  videoTitles: [
    // 'The Indicators',
    'From Mass to the Mountain',
    'Peak Performance: Flying the Fire Boss',
    'Podcast: There I Was with Thomas Middleditch',
    'Real Pilot Story: Hidden Hazard',
    'Real Pilot Story: The Heat of the Moment',
    'Real Pilot Story: Lost Elevator',
    'Real Pilot Story: Pressure Over the Atlantic',
    'Real Pilot Story: No Go-Around',
    'Real Pilot Story: Powerless Over Paris',
    'What are the Costliest Insurance Claims?',
    'Afro Punk Ballet',
    'Meet The Pill Bug',
    "Fox Haven Farm's Herb CSA promo",
    'Beyond Proficient: Flying to Catalina Island',
    'Beyond Proficient: STOL Goal',
    'Beyond Proficient: Extra 300 Series | Part One, Meet the Extra',
    'Beyond Proficient: Extra 300 Series | Part Two, The Flight',
    'Beyond Proficient: Extra 300 Series | Part Three, Intro to Aerobatics',
    'Avoiding Gear-Up Landings',
    'Avoiding Prop Strikes',
    'Avoiding Hard Landings',
    'Avoiding LOC-G',
    'The Low-Phe Life: The Stain',
    'The Low-Phe Life: The Box',
    'The Low-Phe Life: The Trip',
    'The Low-Phe Life: The Test',
    'The Low-Phe Life: The Taste',
    'The Low-Phe Life: The Conversation',
    'How To: Go Wicky-Wacky with Bridge',
  ],
}
